//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDWF.Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChengDuEntities : DbContext
    {
        public ChengDuEntities()
            : base("name=ChengDuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IndustryCategoryDic> IndustryCategoryDics { get; set; }
        public DbSet<RegionInfo> RegionInfoes { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<SportDic> SportDics { get; set; }
        public DbSet<MainData> MainDatas { get; set; }
    }
}
