//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDWF.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainData
    {
        public int ID { get; set; }
        public string ProjectType { get; set; }
        public string ProjectName { get; set; }
        public string ProjectPosition { get; set; }
        public string ProjectProduct { get; set; }
        public Nullable<double> FloorSpace { get; set; }
        public Nullable<double> EmployeesNums { get; set; }
        public Nullable<double> WomenEmployees { get; set; }
        public Nullable<double> AnnualOutputValue { get; set; }
        public string PersonInCharge { get; set; }
        public string ContactInformation { get; set; }
        public string SportType { get; set; }
        public Nullable<double> SportMoney { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public string GBCODE { get; set; }
    }
}
